# Generated by Django 4.2.27 on 2026-01-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
