# Generated by Django 4.2.27 on 2026-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0002_feedback_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_predictions', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('pending_feedback', models.IntegerField(default=0)),
                ('accuracy_rate', models.FloatField(default=100.0)),
                ('real_count', models.IntegerField(default=0)),
                ('fake_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
