# Generated by Django 4.2.27 on 2026-02-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_activitylog'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activitylog',
            table='activity_logs',
        ),
        migrations.AlterModelTable(
            name='dashboardstats',
            table='dashboard_metrics',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='correction_feedbacks',
        ),
        migrations.AlterModelTable(
            name='prediction',
            table='predictions',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='votes',
        ),
    ]
